{
  "openapi" : "3.0.2",
  "info" : {
    "title" : "Dialogporten",
    "version" : "0.0.1"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/Altinn/Dialogporten/0.0.1",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "tags" : [ {
    "name" : "Non-privileged",
    "description" : "Operations available for both end-user systems and service providers"
  }, {
    "name" : "Privileged",
    "description" : "Operations only available service providers"
  } ],
  "paths" : {
    "/dialogporten" : {
      "summary" : "Path used to manage the list of dialogue elements.",
      "description" : "The REST endpoint/path used to list and for service provides to create dialogue elements.  This path contains a `GET` and `POST` operation to perform the list and create tasks, respectively.",
      "get" : {
        "tags" : [ "Non-privileged" ],
        "description" : "API for listing/searching for dialogue elements.",
        "operationId" : "GetDialogueElements",
        "responses" : {
          "200" : {
            "description" : "Successful response - returns an array of dialogue elements.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/DialogueElementRequest"
                  }
                }
              }
            }
          }
        }
      },
      "post" : {
        "tags" : [ "Privileged" ],
        "description" : "Creates a new dialogue element.",
        "operationId" : "CreateDialogueElement",
        "requestBody" : {
          "description" : "A new dialogue element to be created using the `DialogueElementRequest` model",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/DialogueElementRequest"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "Successful response."
          }
        }
      }
    },
    "/dialogporten/{id}" : {
      "summary" : "Path used to manage a single dialogue element.",
      "description" : "The REST endpoint/path used to get, update, and delete single dialogue elements.  This path contains `GET`, `PUT`, `PATCH` and `DELETE` operations used to perform the get, update, and delete tasks, respectively.",
      "get" : {
        "tags" : [ "Non-privileged" ],
        "description" : "Gets the details of a single dialogue element.",
        "operationId" : "GetDialogueElement",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "A unique identifier for a dialogue element.",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "format" : "uuid"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/DialogueElementResponse"
                }
              }
            }
          }
        }
      },
      "put" : {
        "tags" : [ "Privileged" ],
        "description" : "Updates an existing dialogue element.",
        "operationId" : "updateDialogElement",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "A unique identifier for a dialogue element.",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "format" : "uuid"
          }
        } ],
        "requestBody" : {
          "description" : "Updated `DialogElement` information.",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/DialogueElementRequest"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "202" : {
            "description" : "Successful response."
          }
        }
      },
      "delete" : {
        "tags" : [ "Privileged" ],
        "description" : "Deletes an existing dialogue element.",
        "operationId" : "deleteDialogElement",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "A unique identifier for a dialogue element.",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "format" : "uuid"
          }
        } ],
        "responses" : {
          "204" : {
            "description" : "Successful response."
          }
        }
      },
      "patch" : {
        "tags" : [ "Privileged" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "A unique identifier for a dialogue element.",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "format" : "uuid"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/DialogueElementRequest"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "202" : {
            "description" : "The PATCH of the dialogue element was successful"
          }
        }
      }
    },
    "/dialogporten/{id}/notificationlog" : {
      "get" : {
        "tags" : [ "Non-privileged" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "A unique identifier for a dialogue element.",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "format" : "uuid"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/NotificationLog"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "LocalizedString" : {
        "title" : "LocalizedString",
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "string"
          },
          "value" : {
            "type" : "string"
          }
        },
        "description" : "",
        "example" : {
          "code" : "nb_NO",
          "value" : "En eksempel på en tekst på norsk"
        }
      },
      "Actions" : {
        "title" : "Actions",
        "required" : [ "api", "gui" ],
        "type" : "object",
        "properties" : {
          "gui" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/GuiAction"
            }
          },
          "api" : {
            "type" : "array",
            "writeOnly" : false,
            "items" : {
              "$ref" : "#/components/schemas/ApiAction"
            }
          }
        },
        "description" : "",
        "example" : {
          "gui" : [ {
            "action" : "open",
            "type" : "primary",
            "title" : [ {
              "code" : "nb_NO",
              "value" : "Åpne i dialogtjeneste"
            } ],
            "url" : "https://example.com/some/deep/link/to/dialogues/123456789"
          }, {
            "action" : "confirm",
            "requiresAccessToResource" : "somesubresource",
            "type" : "secondary",
            "title" : [ {
              "code" : "nb_NO",
              "value" : "Bekreft mottatt"
            } ],
            "isBackChannel" : true,
            "url" : "https://example.com/some/deep/link/to/dialogues/123456789/confirmReceived"
          }, {
            "action" : "delete",
            "type" : "tertiary",
            "title" : [ {
              "code" : "nb_NO",
              "value" : "Avbryt"
            } ],
            "isDeleteAction" : true,
            "url" : "https://example.com/some/deep/link/to/dialogues/123456789"
          } ],
          "api" : [ {
            "action" : "open",
            "actionUrl" : "https://example.com/api/dialogues/123456789",
            "method" : "GET",
            "responseSchema" : "https://schemas.altinn.no/de/v1/de.json",
            "documentationUrl" : "https://api-docs.example.com/dialogueservice/open-action"
          }, {
            "action" : "confirm",
            "method" : "POST",
            "actionUrl" : "https://example.com/api/dialogues/123456789/confirmReceived",
            "documentationUrl" : "https://api-docs.example.com/dialogueservice/confirm-action"
          }, {
            "action" : "submit",
            "actionUrl" : "https://example.com/api/dialogues/123456789",
            "method" : "POST",
            "requestSchema" : "https://schemas.example.com/dialogueservice/v1/dialogueservice.json",
            "responseSchema" : "https://schemas.altinn.no/de/v1/de.json"
          }, {
            "action" : "delete",
            "method" : "DELETE",
            "actionUrl" : "https://example.com/api/dialogues/123456789"
          } ]
        }
      },
      "GuiAction" : {
        "title" : "GuiAction",
        "type" : "object",
        "properties" : {
          "action" : {
            "type" : "string"
          },
          "requiresAccessToResource" : {
            "type" : "string"
          },
          "type" : {
            "type" : "string"
          },
          "title" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/GuiAction_title"
            }
          },
          "isBackChannel" : {
            "type" : "boolean"
          },
          "url" : {
            "type" : "string"
          }
        },
        "description" : "",
        "example" : {
          "action" : "confirm",
          "requiresAccessToResource" : "somesubresource",
          "type" : "secondary",
          "title" : [ {
            "code" : "nb_NO",
            "value" : "Bekreft mottatt"
          } ],
          "isBackChannel" : true,
          "url" : "https://example.com/some/deep/link/to/dialogues/123456789/confirmReceived"
        }
      },
      "ApiAction" : {
        "title" : "ApiAction",
        "required" : [ "action", "actionUrl" ],
        "type" : "object",
        "properties" : {
          "action" : {
            "type" : "string"
          },
          "actionUrl" : {
            "type" : "string"
          },
          "method" : {
            "type" : "string"
          },
          "requestSchema" : {
            "type" : "string"
          },
          "responseSchema" : {
            "type" : "string"
          },
          "documentationUrl" : {
            "type" : "string"
          }
        },
        "description" : "",
        "example" : {
          "action" : "submit",
          "actionUrl" : "https://example.com/api/dialogues/123456789",
          "method" : "POST",
          "requestSchema" : "https://schemas.example.com/dialogueservice/v1/dialogueservice.json",
          "responseSchema" : "https://schemas.altinn.no/de/v1/de.json",
          "documentationUrl" : "https://api-docs.example.com/dialogueservice/confirm-action"
        }
      },
      "Dates" : {
        "title" : "DialogDates",
        "type" : "object",
        "properties" : {
          "createdDateTime" : {
            "type" : "string",
            "format" : "date-time",
            "readOnly" : false
          },
          "updatedDateTime" : {
            "type" : "string",
            "format" : "date-time"
          },
          "readDateTime" : {
            "type" : "string",
            "format" : "date-time",
            "readOnly" : false
          },
          "dueDateTime" : {
            "type" : "string",
            "format" : "date-time",
            "readOnly" : false
          }
        },
        "description" : "",
        "example" : {
          "createdDateTime" : "2022-12-01T10:00:00.000Z",
          "updatedDateTime" : "2022-12-01T10:00:00.000Z",
          "readDateTime" : "2022-12-01T10:00:00.000Z",
          "dueDateTime" : "2022-12-01T12:00:00.000Z"
        }
      },
      "Configuration" : {
        "title" : "Configuration",
        "type" : "object",
        "properties" : {
          "requireReadNotification" : {
            "type" : "boolean"
          },
          "visibleDateTime" : {
            "type" : "string",
            "format" : "date-time"
          },
          "onLoadDetailsRefreshFromUrl" : {
            "type" : "string"
          },
          "authorization" : {
            "$ref" : "#/components/schemas/ElementAuthorization"
          }
        },
        "description" : "",
        "example" : {
          "requireReadNotification" : true,
          "visibleDateTime" : "2022-12-01T12:00:00.000Z",
          "onLoadDetailsRefreshFromUrl" : "https://example.com/api/dialogues/123456789/get",
          "authorization" : {
            "requirePermitFrom" : "Both",
            "xacmlPolicy" : [ {
              "Effect" : "Permit",
              "Subjects" : [ "person:12345678901" ],
              "Resources" : [ "serviceresource:example_dialogue_service", "serviceresource:example_dialogue_service/attachment1" ],
              "Actions" : [ "open", "confirm", "submit", "delete" ],
              "Description" : "Nærmeste leder har alle tilganger",
              "IsDelegable" : true
            }, {
              "Effect" : "Permit",
              "Subjects" : [ "person:23456789012", "accessgroup:taushetsbelagt" ],
              "Resources" : [ "serviceresource:example_dialogue_service" ],
              "Actions" : [ "open" ],
              "Description" : "Den aktuelle ansatte, samt bemyndigede medarbeidere, har kun lesetilgang",
              "IsDelegable" : false
            } ]
          }
        }
      },
      "ElementAuthorization" : {
        "title" : "ElementAuthorization",
        "required" : [ "requirePermitFrom" ],
        "type" : "object",
        "properties" : {
          "requirePermitFrom" : {
            "type" : "string",
            "enum" : [ "Both", "Either", "InlineOnly" ]
          },
          "xacmlPolicy" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/XacmlRule"
            }
          }
        },
        "description" : "",
        "example" : {
          "requirePermitFrom" : "Both",
          "xacmlPolicy" : [ {
            "Effect" : "Permit",
            "Subjects" : [ "person:12345678901" ],
            "Resources" : [ "serviceresource:example_dialogue_service", "serviceresource:example_dialogue_service/attachment1" ],
            "Actions" : [ "open", "confirm", "submit", "delete" ],
            "Description" : "Nærmeste leder har alle tilganger",
            "IsDelegable" : true
          }, {
            "Effect" : "Permit",
            "Subjects" : [ "person:23456789012", "accessgroup:taushetsbelagt" ],
            "Resources" : [ "serviceresource:example_dialogue_service" ],
            "Actions" : [ "open" ],
            "Description" : "Den aktuelle ansatte, samt bemyndigede medarbeidere, har kun lesetilgang",
            "IsDelegable" : false
          } ]
        }
      },
      "XacmlRule" : {
        "title" : "XacmlRule",
        "type" : "object",
        "properties" : {
          "Effect" : {
            "type" : "string"
          },
          "Subjects" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "Resources" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "Actions" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "Description" : {
            "type" : "string"
          },
          "IsDelegable" : {
            "type" : "boolean"
          }
        },
        "description" : "",
        "example" : {
          "Effect" : "Permit",
          "Subjects" : [ "person:12345678901" ],
          "Resources" : [ "serviceresource:example_dialogue_service", "serviceresource:example_dialogue_service/attachment1" ],
          "Actions" : [ "open", "confirm", "submit", "delete" ],
          "Description" : "Nærmeste leder har alle tilganger",
          "IsDelegable" : true
        }
      },
      "Content" : {
        "title" : "Content",
        "required" : [ "body", "title" ],
        "type" : "object",
        "properties" : {
          "body" : {
            "$ref" : "#/components/schemas/LocalizedStrings"
          },
          "title" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/LocalizedString"
            }
          },
          "senderName" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/LocalizedString"
            }
          }
        },
        "description" : "",
        "example" : {
          "body" : [ {
            "code" : "nb_NO",
            "value" : "Innhold med <em>begrenset</em> HTML-støtte. Dette innholdet vises når elementet ekspanderes."
          } ],
          "title" : [ {
            "code" : "nb_NO",
            "value" : "En eksempel på en tittel"
          } ],
          "senderName" : [ {
            "code" : "nb_NO",
            "value" : "Overstyrt avsendernavn (bruker default tjenesteeiers navn)"
          } ]
        }
      },
      "Attachment" : {
        "title" : "Attachment",
        "required" : [ "displayName", "url" ],
        "type" : "object",
        "properties" : {
          "displayName" : {
            "$ref" : "#/components/schemas/LocalizedStrings"
          },
          "sizeInBytes" : {
            "type" : "integer",
            "format" : "int32"
          },
          "contentType" : {
            "type" : "string"
          },
          "url" : {
            "type" : "string"
          },
          "requiresAccessToResource" : {
            "type" : "string"
          }
        },
        "description" : "",
        "example" : {
          "displayName" : [ {
            "code" : "nb_NO",
            "value" : "dette er et vedlegg"
          } ],
          "sizeInBytes" : 123456,
          "contentType" : "application/pdf",
          "url" : "https://example.com/api/dialogues/123456789/attachments/1",
          "requiresAccessToResource" : "attachment1"
        }
      },
      "NotificationLog" : {
        "title" : "NotificationLog",
        "type" : "object",
        "properties" : {
          "sms" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/NotificationLogSms"
            }
          },
          "email" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/NotificationLogEmail"
            }
          },
          "push" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/NotificationLogPush"
            }
          }
        },
        "description" : "",
        "example" : {
          "sms" : [ {
            "sentDateTime" : "2022-12-01T10:00:00.000Z",
            "status" : "pending",
            "notification" : {
              "text" : "dette kommer på sms",
              "from" : "Etaten"
            }
          } ],
          "email" : [ {
            "sentDateTime" : "2022-12-01T10:00:00.000Z",
            "status" : "ok",
            "notification" : {
              "subject" : "emnefeltet på e-post",
              "template" : "some-email-template",
              "tokens" : [ {
                "name" : "header",
                "value" : "dette er en header"
              }, {
                "name" : "body",
                "value" : "Hei {{recipient.fullname}}!"
              } ]
            }
          } ],
          "push" : [ {
            "sentDateTime" : "2022-12-01T10:00:00.000Z",
            "status" : "ok",
            "notification" : {
              "title" : "Notification title",
              "body" : "Simple piece of body text.\nSecond line of body text :)",
              "icon" : "https://example.com/some-icon-atleast-192x192.png",
              "notificationClickUrl" : "https://example.com/some/deep/link/to/dialogues/123456789"
            }
          } ]
        }
      },
      "Links" : {
        "title" : "Links",
        "type" : "object",
        "properties" : {
          "self" : {
            "$ref" : "#/components/schemas/LinkHref"
          },
          "notificationlog" : {
            "$ref" : "#/components/schemas/LinkHref"
          },
          "activitylog" : {
            "$ref" : "#/components/schemas/LinkHref"
          },
          "serviceresource" : {
            "$ref" : "#/components/schemas/LinkHref"
          },
          "selfgui" : {
            "$ref" : "#/components/schemas/LinkHref"
          },
          "externalgui" : {
            "$ref" : "#/components/schemas/LinkHref"
          }
        },
        "description" : "",
        "example" : {
          "self" : {
            "href" : "/dialogporten/api/v1/de/e0300961-85fb-4ef2-abff-681d77f9960e"
          },
          "notificationlog" : {
            "href" : "/dialogporten/api/v1/de/e0300961-85fb-4ef2-abff-681d77f9960e/notificationlog"
          },
          "serviceresource" : {
            "href" : "/resourceregistry/api/v1/resource/example_dialogue_service/"
          },
          "selfgui" : {
            "href" : "https://www.dialogporten.no/?expandElement=e0300961-85fb-4ef2-abff-681d77f9960e"
          },
          "externalgui" : {
            "href" : "https://example.com/some/deep/link/to/dialogues/123456789"
          }
        }
      },
      "LinkHref" : {
        "title" : "LinkHref",
        "type" : "object",
        "properties" : {
          "href" : {
            "type" : "string"
          }
        },
        "description" : "",
        "example" : {
          "href" : "/dialogporten/api/v1/de/e0300961-85fb-4ef2-abff-681d77f9960e"
        }
      },
      "LocalizedStrings" : {
        "type" : "array",
        "description" : "",
        "items" : {
          "$ref" : "#/components/schemas/LocalizedString"
        }
      },
      "NotificationStatus" : {
        "type" : "string",
        "description" : "",
        "enum" : [ "Ok", "Pending", "Failed" ]
      },
      "ActivityLog" : {
        "title" : "ActivityLog",
        "required" : [ "activityDateTime", "activityDescription", "activityType" ],
        "type" : "object",
        "properties" : {
          "activityDateTime" : {
            "type" : "string",
            "format" : "date-time"
          },
          "activityType" : {
            "type" : "string",
            "enum" : [ "change", "feedback" ]
          },
          "performedBy" : {
            "type" : "string"
          },
          "activityDescription" : {
            "$ref" : "#/components/schemas/LocalizedStrings"
          },
          "activityDetailsUrl" : {
            "type" : "string"
          }
        },
        "description" : "",
        "example" : {
          "activityDateTime" : "2022-12-01T10:00:00.000Z",
          "activityType" : "feedback",
          "performedBy" : "person:12018212345",
          "activityDescription" : [ {
            "code" : "nb_NO",
            "value" : "Foreløpig svar på saksbehandling"
          } ],
          "activityDetailsUrl" : "https://example.com/some/deep/link/to/dialogues/123456789/message/2"
        }
      },
      "DialogueElementResponse" : {
        "title" : "DialogElementResponse",
        "required" : [ "status" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string"
          },
          "serviceResourceIdentifier" : {
            "type" : "string"
          },
          "externalReference" : {
            "type" : "string"
          },
          "dialogueGroup" : {
            "$ref" : "#/components/schemas/DialogueGroup"
          },
          "recipient" : {
            "type" : "string"
          },
          "status" : {
            "$ref" : "#/components/schemas/Status"
          },
          "dates" : {
            "$ref" : "#/components/schemas/Dates"
          },
          "content" : {
            "$ref" : "#/components/schemas/Content"
          },
          "attachments" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Attachment"
            }
          },
          "actions" : {
            "$ref" : "#/components/schemas/Actions"
          },
          "configuration" : {
            "$ref" : "#/components/schemas/Configuration"
          },
          "_links" : {
            "$ref" : "#/components/schemas/Links"
          },
          "activityLog" : {
            "type" : "array",
            "description" : "",
            "items" : {
              "$ref" : "#/components/schemas/ActivityLog"
            }
          }
        },
        "description" : "",
        "example" : {
          "id" : "e0300961-85fb-4ef2-abff-681d77f9960e",
          "serviceResourceIdentifier" : "example_dialogue_service",
          "externalReference" : "123456789",
          "dialogueGroup" : {
            "id" : "some-arbitrary-id",
            "order" : 1,
            "name" : [ {
              "lang" : "nb_NO",
              "value" : "Navn på dialoggruppe."
            } ]
          },
          "recipient" : "org:991825827",
          "status" : "under-progress",
          "dates" : {
            "createdDateTime" : "2022-12-01T10:00:00.000Z",
            "updatedDateTime" : "2022-12-01T10:00:00.000Z",
            "readDateTime" : "2022-12-01T10:00:00.000Z",
            "dueDateTime" : "2022-12-01T12:00:00.000Z"
          },
          "content" : {
            "body" : [ {
              "lang" : "nb_NO",
              "value" : "Innhold med <em>begrenset</em> HTML-støtte. Dette innholdet vises når elementet ekspanderes."
            } ],
            "title" : [ {
              "lang" : "nb_NO",
              "value" : "En eksempel på en tittel"
            } ],
            "senderName" : [ {
              "lang" : "nb_NO",
              "value" : "Overstyrt avsendernavn (bruker default tjenesteeiers navn)"
            } ]
          },
          "attachments" : [ {
            "displayName" : [ {
              "lang" : "nb_NO",
              "value" : "dette er et vedlegg"
            } ],
            "sizeInBytes" : 123456,
            "contentType" : "application/pdf",
            "url" : "https://example.com/api/dialogues/123456789/attachments/1",
            "requiresAccessToResource" : "attachment1"
          } ],
          "actions" : {
            "gui" : [ {
              "action" : "open",
              "type" : "primary",
              "title" : [ {
                "lang" : "nb_NO",
                "value" : "Åpne i dialogtjeneste"
              } ],
              "url" : "https://example.com/some/deep/link/to/dialogues/123456789"
            }, {
              "action" : "confirm",
              "requiresAccessToResource" : "somesubresource",
              "type" : "secondary",
              "title" : [ {
                "lang" : "nb_NO",
                "value" : "Bekreft mottatt"
              } ],
              "isBackChannel" : true,
              "url" : "https://example.com/some/deep/link/to/dialogues/123456789/confirmReceived"
            }, {
              "action" : "delete",
              "type" : "tertiary",
              "title" : [ {
                "lang" : "nb_NO",
                "value" : "Avbryt"
              } ],
              "isDeleteAction" : true,
              "url" : "https://example.com/some/deep/link/to/dialogues/123456789"
            } ],
            "api" : [ {
              "action" : "open",
              "actionUrl" : "https://example.com/api/dialogues/123456789",
              "method" : "GET",
              "responseSchema" : "https://schemas.altinn.no/de/v1/de.json",
              "documentationUrl" : "https://api-docs.example.com/dialogueservice/open-action"
            }, {
              "action" : "confirm",
              "method" : "POST",
              "actionUrl" : "https://example.com/api/dialogues/123456789/confirmReceived",
              "documentationUrl" : "https://api-docs.example.com/dialogueservice/confirm-action"
            }, {
              "action" : "submit",
              "actionUrl" : "https://example.com/api/dialogues/123456789",
              "method" : "POST",
              "requestSchema" : "https://schemas.example.com/dialogueservice/v1/dialogueservice.json",
              "responseSchema" : "https://schemas.altinn.no/de/v1/de.json"
            }, {
              "action" : "delete",
              "method" : "DELETE",
              "actionUrl" : "https://example.com/api/dialogues/123456789"
            } ]
          },
          "configuration" : {
            "requireReadNotification" : true,
            "visibleDateTime" : "2022-12-01T12:00:00.000Z",
            "onLoadDetailsRefreshFromUrl" : "https://example.com/api/dialogues/123456789/get",
            "authorization" : {
              "requirePermitFrom" : "Both",
              "xacmlPolicy" : [ {
                "Effect" : "Permit",
                "Subjects" : [ "person:12345678901" ],
                "Resources" : [ "serviceresource:example_dialogue_service", "serviceresource:example_dialogue_service/attachment1" ],
                "Actions" : [ "open", "confirm", "submit", "delete" ],
                "Description" : "Nærmeste leder har alle tilganger",
                "IsDelegable" : true
              }, {
                "Effect" : "Permit",
                "Subjects" : [ "person:23456789012", "accessgroup:taushetsbelagt" ],
                "Resources" : [ "serviceresource:example_dialogue_service" ],
                "Actions" : [ "open" ],
                "Description" : "Den aktuelle ansatte, samt bemyndigede medarbeidere, har kun lesetilgang",
                "IsDelegable" : false
              } ]
            }
          },
          "activityLog" : [ {
            "activityDateTime" : "2022-12-01T10:00:00.000Z",
            "activityType" : "change",
            "performedBy" : "person:12018212345",
            "activityDescription" : [ {
              "lang" : "nb_NO",
              "value" : "Dokumentet 'X' ble signert og kan sendes inn"
            } ],
            "activityDetailsUrl" : "https://example.com/some/deep/link/to/dialogues/123456789/activitylog/1"
          }, {
            "activityDateTime" : "2022-12-01T10:00:00.000Z",
            "activityType" : "feedback",
            "activityDescription" : [ {
              "lang" : "nb_NO",
              "value" : "Foreløpig svar på saksbehandling"
            } ],
            "activityDetailsUrl" : "https://example.com/some/deep/link/to/dialogues/123456789/message/2"
          } ],
          "_links" : {
            "self" : {
              "href" : "/dialogporten/api/v1/de/e0300961-85fb-4ef2-abff-681d77f9960e"
            },
            "notificationlog" : {
              "href" : "/dialogporten/api/v1/de/e0300961-85fb-4ef2-abff-681d77f9960e/notificationlog"
            },
            "serviceresource" : {
              "href" : "/resourceregistry/api/v1/resource/example_dialogue_service/"
            },
            "selfgui" : {
              "href" : "https://www.dialogporten.no/?expandElement=e0300961-85fb-4ef2-abff-681d77f9960e"
            },
            "externalgui" : {
              "href" : "https://example.com/some/deep/link/to/dialogues/123456789"
            }
          }
        }
      },
      "DialogueGroup" : {
        "title" : "DialogGroup",
        "required" : [ "id", "name" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string"
          },
          "order" : {
            "type" : "integer",
            "format" : "int32"
          },
          "name" : {
            "$ref" : "#/components/schemas/LocalizedStrings"
          }
        },
        "description" : "",
        "example" : {
          "id" : "some-arbitrary-id",
          "order" : 1,
          "name" : [ {
            "lang" : "nb_NO",
            "value" : "Navn på dialoggruppe."
          } ]
        }
      },
      "Status" : {
        "type" : "string",
        "description" : "",
        "enum" : [ "unspecified", "under-progress", "waiting", "signing", "cancelled", "completed" ]
      },
      "NotificationRequest" : {
        "title" : "Notifications",
        "type" : "object",
        "properties" : {
          "sms" : {
            "$ref" : "#/components/schemas/NotificationRequestSms"
          },
          "email" : {
            "$ref" : "#/components/schemas/NotificationRequestEmail"
          },
          "push" : {
            "$ref" : "#/components/schemas/NotificationRequestPush"
          }
        },
        "description" : "",
        "example" : {
          "sms" : {
            "text" : [ {
              "code" : "nb_NO",
              "value" : "dette kommer på sms"
            } ],
            "from" : [ {
              "code" : "nb_NO",
              "value" : "Etaten"
            } ]
          },
          "email" : {
            "subject" : [ {
              "code" : "nb_NO",
              "value" : "emnefeltet på e-post"
            } ],
            "template" : "some-email-template",
            "tokens" : [ {
              "name" : "header",
              "value" : [ {
                "code" : "nb_NO",
                "value" : "dette er en header"
              } ]
            }, {
              "name" : "body",
              "value" : [ {
                "code" : "nb_NO",
                "value" : "Hei {{recipient.fullname}}!"
              } ]
            } ]
          },
          "push" : {
            "sentDateTime" : "2022-12-01T10:00:00.000Z",
            "status" : "ok",
            "notification" : {
              "title" : [ {
                "code" : "nb_NO",
                "value" : "Tittel på notifikasjon"
              } ],
              "body" : [ {
                "code" : "nb_NO",
                "value" : "Dette er første linje\nDette er andre linje, sendt til {{recipient.fullname}}"
              } ],
              "icon" : "https://example.com/some-icon-atleast-192x192.png",
              "notificationClickUrl" : "https://example.com/some/deep/link/to/dialogues/123456789"
            }
          }
        }
      },
      "NotificationRequestSms" : {
        "title" : "NotificationSms",
        "required" : [ "from", "text" ],
        "type" : "object",
        "properties" : {
          "text" : {
            "$ref" : "#/components/schemas/LocalizedStrings"
          },
          "from" : {
            "$ref" : "#/components/schemas/LocalizedStrings"
          }
        },
        "description" : "",
        "example" : {
          "text" : [ {
            "code" : "nb_NO",
            "value" : "dette kommer på sms"
          } ],
          "from" : [ {
            "code" : "nb_NO",
            "value" : "Etaten"
          } ]
        }
      },
      "NotificationLogEmail" : {
        "title" : "EmailNotificationLog",
        "type" : "object",
        "properties" : {
          "sentDateTime" : {
            "type" : "string",
            "format" : "date-time"
          },
          "status" : {
            "type" : "string"
          },
          "notification" : {
            "$ref" : "#/components/schemas/NotificationLogEmailPayload"
          }
        },
        "description" : "",
        "example" : {
          "sentDateTime" : "2022-12-01T10:00:00.000Z",
          "status" : "ok",
          "notification" : {
            "subject" : "emnefeltet på e-post",
            "template" : "some-email-template",
            "tokens" : [ {
              "name" : "header",
              "value" : "dette er en header"
            }, {
              "name" : "body",
              "value" : "Hei {{recipient.fullname}}!"
            } ]
          }
        }
      },
      "NotificationLogPush" : {
        "title" : "PushNotificationLog",
        "type" : "object",
        "properties" : {
          "sentDateTime" : {
            "type" : "string",
            "format" : "date-time"
          },
          "status" : {
            "$ref" : "#/components/schemas/NotificationStatus"
          },
          "notification" : {
            "$ref" : "#/components/schemas/NotificationLogPushPayload"
          }
        },
        "description" : "",
        "example" : {
          "sentDateTime" : "2022-12-01T10:00:00.000Z",
          "status" : "ok",
          "notification" : {
            "title" : "Notification title",
            "body" : "Simple piece of body text.\nSecond line of body text :)",
            "icon" : "https://example.com/some-icon-atleast-192x192.png",
            "notificationClickUrl" : "https://example.com/some/deep/link/to/dialogues/123456789"
          }
        }
      },
      "NotificationLogSms" : {
        "title" : "SmsNotificationLog",
        "type" : "object",
        "properties" : {
          "sentDateTime" : {
            "type" : "string",
            "format" : "date-time"
          },
          "status" : {
            "$ref" : "#/components/schemas/NotificationStatus"
          },
          "notification" : {
            "$ref" : "#/components/schemas/NotificationLogSmsPayload"
          }
        },
        "description" : "",
        "example" : {
          "sentDateTime" : "2022-12-01T10:00:00.000Z",
          "status" : "pending",
          "notification" : {
            "text" : "dette kommer på sms",
            "from" : "Etaten"
          }
        }
      },
      "NotificationLogEmailPayload" : {
        "title" : "NotificationLogEmailPayload",
        "type" : "object",
        "properties" : {
          "subject" : {
            "type" : "string"
          },
          "template" : {
            "type" : "string"
          },
          "tokens" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/NotificationLogEmailPayloadToken"
            }
          }
        },
        "description" : "",
        "example" : {
          "subject" : "emnefeltet på e-post",
          "template" : "some-email-template",
          "tokens" : [ {
            "name" : "header",
            "value" : "dette er en header"
          }, {
            "name" : "body",
            "value" : "Hei {{recipient.fullname}}!"
          } ]
        }
      },
      "NotificationLogEmailPayloadToken" : {
        "title" : "NotificationLogEmailPayloadToken",
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "value" : {
            "type" : "string"
          }
        },
        "description" : "",
        "example" : {
          "name" : "body",
          "value" : "Hei {{recipient.fullname}}!"
        }
      },
      "NotificationLogPushPayload" : {
        "title" : "NotificationLogPushPayload",
        "type" : "object",
        "properties" : {
          "title" : {
            "type" : "string"
          },
          "body" : {
            "type" : "string"
          },
          "icon" : {
            "type" : "string"
          },
          "notificationClickUrl" : {
            "type" : "string"
          }
        },
        "description" : "",
        "example" : {
          "title" : "Notification title",
          "body" : "Simple piece of body text.\nSecond line of body text :)",
          "icon" : "https://example.com/some-icon-atleast-192x192.png",
          "notificationClickUrl" : "https://example.com/some/deep/link/to/dialogues/123456789"
        }
      },
      "NotificationLogSmsPayload" : {
        "title" : "NotificationLogSmsPayload",
        "type" : "object",
        "properties" : {
          "text" : {
            "type" : "string"
          },
          "from" : {
            "type" : "string"
          }
        },
        "description" : "",
        "example" : {
          "text" : "dette kommer på sms",
          "from" : "Etaten"
        }
      },
      "NotificationRequestEmail" : {
        "title" : "NotificationRequestEmail",
        "type" : "object",
        "properties" : {
          "subject" : {
            "$ref" : "#/components/schemas/LocalizedStrings"
          },
          "template" : {
            "type" : "string"
          },
          "tokens" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/NotificationRequestEmailToken"
            }
          }
        },
        "description" : "",
        "example" : {
          "subject" : [ {
            "code" : "nb_NO",
            "value" : "emnefeltet på e-post"
          } ],
          "template" : "some-email-template",
          "tokens" : [ {
            "name" : "header",
            "value" : [ {
              "code" : "nb_NO",
              "value" : "dette er en header"
            } ]
          }, {
            "name" : "body",
            "value" : [ {
              "code" : "nb_NO",
              "value" : "Hei {{recipient.fullname}}!"
            } ]
          } ]
        }
      },
      "NotificationRequestEmailToken" : {
        "title" : "NotificationRequestEmailToken",
        "required" : [ "name", "value" ],
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "value" : {
            "$ref" : "#/components/schemas/LocalizedStrings"
          }
        },
        "description" : "",
        "example" : {
          "name" : "body",
          "value" : [ {
            "code" : "nb_NO",
            "value" : "Hei {{recipient.fullname}}!"
          } ]
        }
      },
      "NotificationRequestPush" : {
        "title" : "NotificationRequestPush",
        "type" : "object",
        "properties" : {
          "title" : {
            "$ref" : "#/components/schemas/LocalizedStrings"
          },
          "body" : {
            "$ref" : "#/components/schemas/LocalizedStrings"
          },
          "icon" : {
            "type" : "string"
          },
          "notificationClickUrl" : {
            "type" : "string"
          }
        },
        "description" : "",
        "example" : {
          "title" : [ {
            "code" : "nb_NO",
            "value" : "Tittel på notifikasjon"
          } ],
          "body" : [ {
            "code" : "nb_NO",
            "value" : "Dette er første linje\nDette er andre linje, sendt til {{recipient.fullname}}"
          } ],
          "icon" : "https://example.com/some-icon-atleast-192x192.png",
          "notificationClickUrl" : "https://example.com/some/deep/link/to/dialogues/123456789"
        }
      },
      "DialogueElementRequest" : {
        "title" : "DialogElement",
        "type" : "object",
        "properties" : {
          "serviceResourceIdentifier" : {
            "type" : "string"
          },
          "externalReference" : {
            "type" : "string"
          },
          "dialogueGroup" : {
            "$ref" : "#/components/schemas/DialogueGroup"
          },
          "recipient" : {
            "type" : "string"
          },
          "status" : {
            "$ref" : "#/components/schemas/Status"
          },
          "content" : {
            "$ref" : "#/components/schemas/Content"
          },
          "attachments" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Attachment"
            }
          },
          "actions" : {
            "$ref" : "#/components/schemas/Actions"
          },
          "configuration" : {
            "$ref" : "#/components/schemas/Configuration"
          },
          "activityLog" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/ActivityLog"
            }
          },
          "notifications" : {
            "$ref" : "#/components/schemas/NotificationRequest"
          }
        },
        "description" : "",
        "example" : {
          "serviceResourceIdentifier" : "example_dialogue_service",
          "recipient" : "org:991825827",
          "externalReference" : "123456789",
          "dialogueGroup" : {
            "id" : "some-arbitrary-id",
            "order" : 1,
            "name" : [ {
              "code" : "nb_NO",
              "value" : "Navn på dialoggruppe."
            } ]
          },
          "status" : "under-progress",
          "dates" : {
            "dueDateTime" : "2022-12-01T12:00:00.000Z",
            "expiryDate" : "2023-12-01T12:00:00.000Z"
          },
          "content" : {
            "body" : [ {
              "code" : "nb_NO",
              "value" : "Innhold med <em>begrenset</em> HTML-støtte. Dette innholdet vises når elementet ekspanderes."
            } ],
            "title" : [ {
              "code" : "nb_NO",
              "value" : "En eksempel på en tittel"
            } ],
            "senderName" : [ {
              "code" : "nb_NO",
              "value" : "Overstyrt avsendernavn (bruker default tjenesteeiers navn)"
            } ]
          },
          "attachments" : [ {
            "displayName" : [ {
              "code" : "nb_NO",
              "value" : "dette er et vedlegg"
            } ],
            "sizeInBytes" : 123456,
            "contentType" : "application/pdf",
            "url" : "https://example.com/api/dialogues/123456789/attachments/1",
            "requiresAccessToResource" : "attachment1"
          } ],
          "actions" : {
            "gui" : [ {
              "action" : "open",
              "type" : "primary",
              "title" : [ {
                "code" : "nb_NO",
                "value" : "Åpne i dialogtjeneste"
              } ],
              "url" : "https://example.com/some/deep/link/to/dialogues/123456789"
            }, {
              "action" : "confirm",
              "requiresAccessToResource" : "somesubresource",
              "type" : "secondary",
              "title" : [ {
                "code" : "nb_NO",
                "value" : "Bekreft mottatt"
              } ],
              "isBackChannel" : true,
              "url" : "https://example.com/some/deep/link/to/dialogues/123456789/confirmReceived"
            }, {
              "action" : "delete",
              "type" : "tertiary",
              "title" : [ {
                "code" : "nb_NO",
                "value" : "Avbryt"
              } ],
              "isDeleteAction" : true,
              "url" : "https://example.com/some/deep/link/to/dialogues/123456789"
            } ],
            "api" : [ {
              "action" : "open",
              "actionUrl" : "https://example.com/api/dialogues/123456789",
              "method" : "GET",
              "responseSchema" : "https://schemas.altinn.no/de/v1/de.json",
              "documentationUrl" : "https://api-docs.example.com/dialogueservice/open-action"
            }, {
              "action" : "confirm",
              "method" : "POST",
              "actionUrl" : "https://example.com/api/dialogues/123456789/confirmReceived",
              "documentationUrl" : "https://api-docs.example.com/dialogueservice/confirm-action"
            }, {
              "action" : "submit",
              "actionUrl" : "https://example.com/api/dialogues/123456789",
              "method" : "POST",
              "requestSchema" : "https://schemas.example.com/dialogueservice/v1/dialogueservice.json",
              "responseSchema" : "https://schemas.altinn.no/de/v1/de.json"
            }, {
              "action" : "delete",
              "method" : "DELETE",
              "actionUrl" : "https://example.com/api/dialogues/123456789"
            } ]
          },
          "notifications" : {
            "sms" : {
              "text" : [ {
                "code" : "nb_NO",
                "value" : "dette kommer på sms"
              } ],
              "from" : [ {
                "code" : "nb_NO",
                "value" : "Etaten"
              } ]
            },
            "email" : {
              "subject" : [ {
                "code" : "nb_NO",
                "value" : "emnefeltet på e-post"
              } ],
              "template" : "some-email-template",
              "tokens" : [ {
                "name" : "header",
                "value" : [ {
                  "code" : "nb_NO",
                  "value" : "dette er en header"
                } ]
              }, {
                "name" : "body",
                "value" : [ {
                  "code" : "nb_NO",
                  "value" : "Hei {{recipient.fullname}}!"
                } ]
              } ]
            },
            "push" : {
              "sentDateTime" : "2022-12-01T10:00:00.000Z",
              "status" : "ok",
              "notification" : {
                "title" : [ {
                  "code" : "nb_NO",
                  "value" : "Tittel på notifikasjon"
                } ],
                "body" : [ {
                  "code" : "nb_NO",
                  "value" : "Dette er første linje\nDette er andre linje, sendt til {{recipient.fullname}}"
                } ],
                "icon" : "https://example.com/some-icon-atleast-192x192.png",
                "notificationClickUrl" : "https://example.com/some/deep/link/to/dialogues/123456789"
              }
            }
          },
          "activityLog" : [ ],
          "configuration" : {
            "requireReadNotification" : true,
            "visibleDateTime" : "2022-12-01T12:00:00.000Z",
            "onLoadDetailsRefreshFromUrl" : "https://example.com/api/dialogues/123456789/get",
            "authorization" : {
              "requirePermitFrom" : "Both",
              "xacmlPolicy" : [ {
                "Effect" : "Permit",
                "Subjects" : [ "person:12345678901" ],
                "Resources" : [ "serviceresource:example_dialogue_service", "serviceresource:example_dialogue_service/attachment1" ],
                "Actions" : [ "open", "confirm", "submit", "delete" ],
                "Description" : "Nærmeste leder har alle tilganger",
                "IsDelegable" : true
              }, {
                "Effect" : "Permit",
                "Subjects" : [ "person:23456789012", "accessgroup:taushetsbelagt", "scope:someprefix:somescopeinmaskinportenoridporten" ],
                "Resources" : [ "serviceresource:example_dialogue_service" ],
                "Actions" : [ "open" ],
                "Description" : "Den aktuelle ansatte, samt bemyndigede medarbeidere, har kun lesetilgang",
                "IsDelegable" : false
              } ]
            }
          }
        }
      },
      "GuiAction_title" : {
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "string"
          },
          "value" : {
            "type" : "string"
          }
        }
      }
    },
    "responses" : {
      "DialogElementResponse" : {
        "description" : "",
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/DialogueElementResponse"
            }
          }
        }
      },
      "NotificationLogResponse" : {
        "description" : "",
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/NotificationLog"
            }
          }
        }
      }
    }
  }
}